---

- ansible.builtin.set_fact:
    matrix_client_thirdroom_url_endpoint_public: "https://{{ matrix_server_fqn_thirdroom }}/config.json"

- name: Check Thirdroom
  ansible.builtin.uri:
    url: "{{ matrix_client_thirdroom_url_endpoint_public }}"
    follow_redirects: none
    validate_certs: "{{ matrix_client_thirdroom_self_check_validate_certificates }}"
  register: matrix_client_thirdroom_self_check_result
  check_mode: false
  ignore_errors: true
  delegate_to: 127.0.0.1
  become: false

- name: Fail if Thirdroom not working
  ansible.builtin.fail:
    msg: "Failed checking Thirdroom is up at `{{ matrix_server_fqn_thirdroom }}` (checked endpoint: `{{ matrix_client_thirdroom_url_endpoint_public }}`). Is Thirdroom running? Is port 443 open in your firewall? Full error: {{ matrix_client_thirdroom_self_check_result }}"
  when: "matrix_client_thirdroom_self_check_result.failed or 'json' not in matrix_client_thirdroom_self_check_result"

- name: Report working Thirdroom
  ansible.builtin.debug:
    msg: "Thirdroom at `{{ matrix_server_fqn_thirdroom }}` is working (checked endpoint: `{{ matrix_client_thirdroom_url_endpoint_public }}`)"
